local lsp = require('lspconfig')
require('mason').setup({})
require('fidget').setup({})

lsp.pyright.setup({})
lsp.rust_analyzer.setup({})
lsp.lua_ls.setup({})
lsp.texlab.setup({})
lsp.jdtls.setup({})
lsp.svelte.setup({})
lsp.tsserver.setup({})
lsp.html.setup({})
lsp.cssls.setup({})
lsp.clangd.setup({})
lsp.cmake.setup({})
lsp.zls.setup({})
